import { v4 as uuid } from 'uuid';

export interface Children {
  id: string;
  title: string;
}

export enum types {
  azuki = 'azuki',
  bean = 'bean',
}

const generatorPath = (path: string): string => {
  return `/images/filters/black/${path}`;
};

const galleryFilterList: {
  // [key: string]: number | string | object;
  id: string;
  image: {
    [key: string]: string;
    bean: string;
    azuki: string;
  };
  title: string;
  types: Array<types.azuki | types.bean>;
  children: {
    [key: string]: Children[];
    bean: Children[];
    azuki: Children[];
  };
}[] = [
  {
    id: uuid(),
    image: {
      azuki: '',
      bean: generatorPath('hand.png'),
    },
    title: 'Hand',
    types: [types.bean],
    children: {
      azuki: [],
      bean: [
        {
          id: uuid(),
          title: 'red katana',
        },
        {
          id: uuid(),
          title: 'red katana sheathed',
        },
        {
          id: uuid(),
          title: 'cocktail umbrella',
        },
        {
          id: uuid(),
          title: 'green katana',
        },
        {
          id: uuid(),
          title: 'shinai',
        },
        {
          id: uuid(),
          title: 'fan',
        },
        {
          id: uuid(),
          title: 'ledger',
        },
        {
          id: uuid(),
          title: 'toothpick',
        },
        {
          id: uuid(),
          title: 'bat',
        },
      ],
    },
  },
  {
    id: uuid(),
    image: {
      azuki: '',
      bean: generatorPath('shoe.png'),
    },
    title: 'shoe',
    types: [types.bean],
    children: {
      azuki: [],
      bean: [
        {
          id: uuid(),
          title: 'red chucks',
        },
        {
          id: uuid(),
          title: 'blue sneakers',
        },
        {
          id: uuid(),
          title: 'black chucks',
        },
        {
          id: uuid(),
          title: 'black high tops',
        },
        {
          id: uuid(),
          title: 'brown boots',
        },
        {
          id: uuid(),
          title: 'white sneakers',
        },
        {
          id: uuid(),
          title: 'orange high tops',
        },
        {
          id: uuid(),
          title: 'black boots',
        },
        {
          id: uuid(),
          title: 'leather slides',
        },
        {
          id: uuid(),
          title: 'blue camo slides',
        },
        {
          id: uuid(),
          title: 'red slides',
        },
        {
          id: uuid(),
          title: 'sloth slippers',
        },
        {
          id: uuid(),
          title: 'green sandals',
        },
        {
          id: uuid(),
          title: 'white kicks',
        },
        {
          id: uuid(),
          title: 'red panda slippers',
        },
        {
          id: uuid(),
          title: 'red flip flops',
        },
        {
          id: uuid(),
          title: 'yellow kicks',
        },
        {
          id: uuid(),
          title: 'frog flippers',
        },
        {
          id: uuid(),
          title: 'green slip ons',
        },
        {
          id: uuid(),
          title: 'geta',
        },
        {
          id: uuid(),
          title: 'cat slippers',
        },
        {
          id: uuid(),
          title: 'purple sandals',
        },
        {
          id: uuid(),
          title: 'pink slip ons',
        },
        {
          id: uuid(),
          title: 'socks',
        },
        {
          id: uuid(),
          title: 'fiery wheels',
        },
      ],
    },
  },
  {
    id: uuid(),
    image: {
      azuki: '',
      bean: generatorPath('eyebrows.png'),
    },
    title: 'eyebrows',
    types: [types.bean],
    children: {
      azuki: [],
      bean: [
        {
          id: uuid(),
          title: 'angry',
        },
        {
          id: uuid(),
          title: 'concerned',
        },
        {
          id: uuid(),
          title: 'surprised',
        },
        {
          id: uuid(),
          title: 'determined',
        },
        {
          id: uuid(),
          title: 'curious',
        },
        {
          id: uuid(),
          title: 'thick',
        },
        {
          id: uuid(),
          title: 'sad',
        },
        {
          id: uuid(),
          title: 'bushy',
        },
        {
          id: uuid(),
          title: 'happy',
        },
      ],
    },
  },
  {
    id: uuid(),
    image: {
      azuki: '/images/filters/black/azuki/type.png',
      bean: '/images/filters/black/type.png',
    },
    title: 'Type',
    types: [types.azuki, types.bean],
    children: {
      azuki: [
        { id: uuid(), title: 'human' },
        { id: uuid(), title: 'blue' },
        { id: uuid(), title: 'red' },
        { id: uuid(), title: 'spirit' },
      ],
      bean: [
        { id: uuid(), title: 'red bean' },
        { id: uuid(), title: 'lentil' },
        { id: uuid(), title: 'edamame' },
        { id: uuid(), title: 'black bean' },
        { id: uuid(), title: 'blue bean' },
        { id: uuid(), title: 'coffee bean' },
        { id: uuid(), title: 'purple bean' },
        { id: uuid(), title: 'pinto bean' },
        { id: uuid(), title: 'black eyed bean' },
        { id: uuid(), title: 'jelly bean' },
        { id: uuid(), title: 'golden bean' },
        { id: uuid(), title: 'spirit bean' },
        { id: uuid(), title: 'lightning bean' },
        { id: uuid(), title: 'water bean' },
        { id: uuid(), title: 'fire bean' },
        { id: uuid(), title: 'earth bean' },
      ],
    },
  },
  {
    id: uuid(),
    image: {
      azuki: '/images/filters/black/special.png',
      bean: '/images/filters/black/special.png',
    },
    title: 'Special',
    types: [types.azuki, types.bean],
    children: {
      bean: [
        { id: uuid(), title: 'smoke' },
        { id: uuid(), title: 'fireflies' },
        { id: uuid(), title: 'devil wings' },
        { id: uuid(), title: 'angel wings' },
        { id: uuid(), title: 'water' },
        { id: uuid(), title: 'fire' },
        { id: uuid(), title: 'lightning' },
        { id: uuid(), title: 'earth' },
        { id: uuid(), title: 'butterfly' },
        { id: uuid(), title: 'flying cloud' },
        { id: uuid(), title: 'raijin drums' },
        { id: uuid(), title: 'raijin drums with lightning' },
      ],
      azuki: [
        { id: uuid(), title: 'fireflies' },
        { id: uuid(), title: 'butterfly' },
        { id: uuid(), title: 'fox fire' },
        { id: uuid(), title: 'smoke' },
        { id: uuid(), title: 'sakura' },
        { id: uuid(), title: 'fire' },
        { id: uuid(), title: 'earth' },
        { id: uuid(), title: 'water' },
        { id: uuid(), title: 'lightning' },
      ],
    },
  },
  {
    id: uuid(),
    image: {
      azuki: '/images/filters/black/clothing.png',
      bean: '/images/filters/black/clothing.png',
    },
    title: 'clothing',
    types: [types.azuki, types.bean],
    children: {
      azuki: [
        { id: uuid(), title: 'light kimono' },
        { id: uuid(), title: 'maroon yukata' },
        { id: uuid(), title: 'blue kimono' },
        { id: uuid(), title: 'green yukata' },
        { id: uuid(), title: 'turquoise kimono' },
        { id: uuid(), title: 'black yukata' },
        { id: uuid(), title: 'azuki tech jacket' },
        { id: uuid(), title: 'blue floral kimono' },
        { id: uuid(), title: 'red floral kimono' },
        { id: uuid(), title: 'turquoise kimono with bow' },
        { id: uuid(), title: 'lavender kimono with bow' },
        { id: uuid(), title: 'red hoodie' },
        { id: uuid(), title: 'white yukata' },
        { id: uuid(), title: 'white t-shirt' },
        { id: uuid(), title: 'vest' },
        { id: uuid(), title: 'azuki track jacket' },
        { id: uuid(), title: 'blue kimono with bow' },
        { id: uuid(), title: 'dress shirt' },
        { id: uuid(), title: 'white layered yukata' },
        { id: uuid(), title: 'hoodie' },
        { id: uuid(), title: 'fur hoodie' },
        { id: uuid(), title: 'light armor' },
        { id: uuid(), title: 'red ninja top' },
        { id: uuid(), title: 'black hoodie' },
        { id: uuid(), title: 'tank top' },
        { id: uuid(), title: 'suit with turtleneck' },
        { id: uuid(), title: 'hoodie with bag' },
        { id: uuid(), title: 'black bomber' },
        { id: uuid(), title: 'blue bomber' },
        { id: uuid(), title: 'azuki sweater' },
        { id: uuid(), title: 'black kimono' },
        { id: uuid(), title: 'bloody bomber' },
        { id: uuid(), title: 'black qipao' },
        { id: uuid(), title: 'shinto robe' },
        { id: uuid(), title: 'hoshi jacket' },
        { id: uuid(), title: 'black ninja top' },
        { id: uuid(), title: 'blue qipao' },
        { id: uuid(), title: 'tank top with jacket' },
        { id: uuid(), title: 'kimono with jacket' },
        { id: uuid(), title: 'rain jacket' },
        { id: uuid(), title: 'alpine jacket' },
        { id: uuid(), title: 'kimono with straw hat' },
        { id: uuid(), title: 'kung fu shirt' },
        { id: uuid(), title: 'white hoodie' },
        { id: uuid(), title: 'brown yukata' },
        { id: uuid(), title: 'white blazer' },
        { id: uuid(), title: 'bumblebee jacket' },
        { id: uuid(), title: 'red kimono' },
        { id: uuid(), title: 'frog t-shirt' },
        { id: uuid(), title: 'yellow bikini' },
        { id: uuid(), title: 'black blazer' },
        { id: uuid(), title: 'blue bikini' },
        { id: uuid(), title: 'sloth t-shirt' },
        { id: uuid(), title: 'matsuri happi' },
        { id: uuid(), title: 'archer' },
        { id: uuid(), title: 'cat t-shirt' },
        { id: uuid(), title: 'hawaiian shirt' },
        { id: uuid(), title: 'white qipao with fur' },
        { id: uuid(), title: 'red perfecto jacket' },
        { id: uuid(), title: 'denim jacket' },
        { id: uuid(), title: 'red qipao with fur' },
        { id: uuid(), title: 'vegan mink coat' },
        { id: uuid(), title: 'camo hoodie' },
        { id: uuid(), title: 'camo tech jacket' },
        { id: uuid(), title: 'black t-shirt' },
        { id: uuid(), title: 'red panda t-shirt' },
        { id: uuid(), title: 'suikan' },
        { id: uuid(), title: 'pink oversized kimono' },
        { id: uuid(), title: 'black tech jacket' },
        { id: uuid(), title: 'cat kimono' },
        { id: uuid(), title: 'bandage top' },
        { id: uuid(), title: 'frog kimono' },
        { id: uuid(), title: 'red panda kimono' },
        { id: uuid(), title: 'sloth hoodie' },
        { id: uuid(), title: 'frog hoodie' },
        { id: uuid(), title: 'red panda hoodie' },
        { id: uuid(), title: 'sloth kimono' },
        { id: uuid(), title: 'cat hoodie' },
        { id: uuid(), title: 'plated samurai armor' },
        { id: uuid(), title: 'cloud poncho' },
        { id: uuid(), title: 'sloth yukata' },
        { id: uuid(), title: 'frog yukata' },
        { id: uuid(), title: 'straw poncho' },
        { id: uuid(), title: 'red panda yukata' },
        { id: uuid(), title: 'cat yukata' },
        { id: uuid(), title: 'stitched samurai armor' },
        { id: uuid(), title: 'beige poncho' },
        { id: uuid(), title: 'black perfecto jacket' },
        { id: uuid(), title: 'frog kigurumi' },
        { id: uuid(), title: 'black oversized kimono' },
        { id: uuid(), title: 'sloth kigurumi' },
        { id: uuid(), title: 'red panda kigurumi' },
        { id: uuid(), title: 'cat kigurumi' },
        { id: uuid(), title: 'yellow jumpsuit' },
        { id: uuid(), title: 'golden frog kigurumi' },
        { id: uuid(), title: 'golden sloth kigurumi' },
        { id: uuid(), title: 'golden red panda kigurumi' },
        { id: uuid(), title: 'golden cat kigurumi' },
      ],
      bean: [
        { id: uuid(), title: 'oversized white t-shirt' },
        { id: uuid(), title: 'red varsity jacket' },
        { id: uuid(), title: 'red noragi' },
        { id: uuid(), title: 'white qipao' },
        { id: uuid(), title: 'red beanz puffer jacket' },
        { id: uuid(), title: 'white sweater' },
        { id: uuid(), title: 'white green sweatsuit' },
        { id: uuid(), title: 'green hoodie stripes' },
        { id: uuid(), title: 'white puffer vest' },
        { id: uuid(), title: 'white noragi' },
        { id: uuid(), title: 'oversized red beanz logo t-shirt' },
        { id: uuid(), title: 'brown yukata' },
        { id: uuid(), title: 'cross-body bag' },
        { id: uuid(), title: 'black tank top' },
        { id: uuid(), title: 'blue jacket' },
        { id: uuid(), title: 'oversized black beanz graffiti t-shirt' },
        { id: uuid(), title: 'open black and red jacket' },
        { id: uuid(), title: 'pink hoodie with backpack' },
        { id: uuid(), title: 'ikz hoodie up' },
        { id: uuid(), title: 'green yukata' },
        { id: uuid(), title: 'blue camo hoodie with backpack' },
        { id: uuid(), title: 'red hoodie up' },
        { id: uuid(), title: 'black camo jacket' },
        { id: uuid(), title: 'red hoodie zip-up' },
        { id: uuid(), title: 'bathrobe' },
        { id: uuid(), title: 'hawaiian shirt' },
        { id: uuid(), title: 'kung fu suit' },
        { id: uuid(), title: 'black perfecto leather jacket' },
        { id: uuid(), title: 'jacket and brown scarf' },
        { id: uuid(), title: 'tighty whities' },
        { id: uuid(), title: 'black bomber over hoodie' },
        { id: uuid(), title: 'yellow bomber over hoodie' },
        { id: uuid(), title: 'open cat denim jacket' },
        { id: uuid(), title: 'green camo tank top' },
        { id: uuid(), title: 'bean shorts' },
        { id: uuid(), title: 'bead bracelet' },
        {
          id: uuid(),
          title: 'black track jacket with green frog cross-body bag',
        },
        { id: uuid(), title: 'oversized gray t-shirt with red cross-body bag' },
        { id: uuid(), title: 'pink kimono' },
        { id: uuid(), title: 'shirt' },
        { id: uuid(), title: 'white business attire' },
        { id: uuid(), title: 'orange sweat shorts with bag' },
        { id: uuid(), title: 'red sweat shorts' },
        { id: uuid(), title: 'reversible bomber red side' },
        { id: uuid(), title: 'yellow puffer jacket' },
        { id: uuid(), title: 'black business attire' },
        { id: uuid(), title: 'white scrunched hoodie' },
        { id: uuid(), title: 'yellow camo hoodie up' },
        { id: uuid(), title: 'khaki tactical vest' },
        { id: uuid(), title: 'tech shorts' },
        { id: uuid(), title: 'cargo shorts' },
        { id: uuid(), title: 'green varsity jacket' },
        { id: uuid(), title: 'reversible bomber blue side' },
        { id: uuid(), title: 'red panda puffer vest' },
        { id: uuid(), title: 'sloth sweater' },
        { id: uuid(), title: 'white red sweatsuit' },
        { id: uuid(), title: 'green jacket hood up' },
        { id: uuid(), title: 'olive bomber over hoodie' },
        { id: uuid(), title: 'yellow scrunched hoodie' },
        { id: uuid(), title: 'green sweat shorts' },
        { id: uuid(), title: 'blue scrunched hoodie' },
        { id: uuid(), title: 'faux mink coat' },
        { id: uuid(), title: 'sumo belt' },
        { id: uuid(), title: 'red camo jacket' },
        { id: uuid(), title: 'cowboy' },
        { id: uuid(), title: 'purple jacket' },
        { id: uuid(), title: 'bandaids' },
        { id: uuid(), title: 'orange hoodie' },
        { id: uuid(), title: 'mankini' },
        { id: uuid(), title: 'azuki track jacket' },
        { id: uuid(), title: 'red qipao' },
        { id: uuid(), title: 'pink sweater' },
        { id: uuid(), title: 'red bean necklace' },
        { id: uuid(), title: 'dudou' },
        { id: uuid(), title: 'blue flower kimono' },
        { id: uuid(), title: 'black samurai armor' },
        { id: uuid(), title: 'hanbok' },
        { id: uuid(), title: 'oversized frog t-shirt' },
        { id: uuid(), title: 'green full zip hoodie' },
        { id: uuid(), title: 'blue bean necklace' },
        { id: uuid(), title: 'monkey king vest' },
        { id: uuid(), title: 'red samurai armor' },
        { id: uuid(), title: 'kami' },
        { id: uuid(), title: 'oversized sloth t-shirt' },
        { id: uuid(), title: 'oversized red panda t-shirt' },
        { id: uuid(), title: 'white perfecto leather jacket' },
        { id: uuid(), title: 'jiang shi suit' },
        { id: uuid(), title: 'black tactical vest' },
        { id: uuid(), title: 'red panda kigurumi' },
        { id: uuid(), title: 'cat kigurumi' },
        { id: uuid(), title: 'frog kigurumi' },
        { id: uuid(), title: 'yellow jumpsuit' },
        { id: uuid(), title: 'sloth kigurumi' },
        { id: uuid(), title: 'oni full zip hoodie' },
        { id: uuid(), title: 'oversized cat t-shirt' },
        { id: uuid(), title: 'ninja' },
        { id: uuid(), title: 'maneki neko' },
        { id: uuid(), title: 'oversized black t-shirt with gold chain' },
        { id: uuid(), title: 'jacket and rainbow scarf' },
        {
          id: uuid(),
          title: 'oversized blue t-shirt with white cross-body bag',
        },
        { id: uuid(), title: 'golden bead bracelet' },
        { id: uuid(), title: 'golden frog kigurumi' },
        { id: uuid(), title: 'golden cat kigurumi' },
        { id: uuid(), title: 'golden red panda kigurumi' },
        { id: uuid(), title: 'golden sloth kigurumi' },
      ],
    },
  },
  {
    id: uuid(),
    image: {
      azuki: generatorPath('offhand.png'),
      bean: generatorPath('offhand.png'),
    },
    title: 'offhand',
    types: [types.bean, types.azuki],
    children: {
      azuki: [
        { id: uuid(), title: 'katana' },
        { id: uuid(), title: 'banner' },
        { id: uuid(), title: 'sakura katana' },
        { id: uuid(), title: 'leather katana' },
        { id: uuid(), title: 'lantern' },
        { id: uuid(), title: 'bat' },
        { id: uuid(), title: 'bean juice' },
        { id: uuid(), title: 'zanbato' },
        { id: uuid(), title: 'coin' },
        { id: uuid(), title: 'floorsweeper' },
        { id: uuid(), title: 'fan' },
        { id: uuid(), title: 'umbrella' },
        { id: uuid(), title: 'shinai' },
        { id: uuid(), title: 'sake' },
        { id: uuid(), title: 'shuriken' },
        { id: uuid(), title: 'fishing rod' },
        { id: uuid(), title: 'monk staff' },
        { id: uuid(), title: 'monkey king staff' },
        { id: uuid(), title: 'kanabo' },
        { id: uuid(), title: 'boombox' },
        { id: uuid(), title: 'bokken' },
        { id: uuid(), title: 'guitar' },
        { id: uuid(), title: 'hand seal' },
        { id: uuid(), title: 'hand wrap' },
        { id: uuid(), title: 'hook sword' },
        { id: uuid(), title: 'gloves' },
        { id: uuid(), title: 'skateboard' },
        { id: uuid(), title: 'talisman' },
        { id: uuid(), title: 'lightning orb' },
        { id: uuid(), title: 'fireball' },
        { id: uuid(), title: 'red bean' },
        { id: uuid(), title: 'water orb' },
        { id: uuid(), title: 'earth' },
        { id: uuid(), title: 'blue bean' },
        { id: uuid(), title: 'golden bean' },
        { id: uuid(), title: 'golden kanabo' },
        { id: uuid(), title: 'golden guitar' },
        { id: uuid(), title: 'golden boombox' },
        { id: uuid(), title: 'golden floorsweeper' },
        { id: uuid(), title: 'golden fan' },
        { id: uuid(), title: 'golden hook sword' },
        { id: uuid(), title: 'golden shinai' },
        { id: uuid(), title: 'golden monk staff' },
        { id: uuid(), title: 'golden shuriken' },
        { id: uuid(), title: 'golden skateboard' },
        { id: uuid(), title: 'golden ticket' },
        { id: uuid(), title: 'golden bat' },
        { id: uuid(), title: 'golden umbrella' },
        { id: uuid(), title: 'golden fishing rod' },
        { id: uuid(), title: 'golden katana' },
        { id: uuid(), title: 'golden sheathed katana' },
        { id: uuid(), title: 'golden monkey king staff' },
        { id: uuid(), title: 'golden zanbato' },
      ],
      bean: [
        { id: uuid(), title: 'zanbato' },
        { id: uuid(), title: 'pencil' },
        { id: uuid(), title: 'banner' },
        { id: uuid(), title: 'cocktail umbrella' },
        { id: uuid(), title: 'spray paint' },
        { id: uuid(), title: 'axe' },
        { id: uuid(), title: 'twig' },
        { id: uuid(), title: 'dumbbell' },
        { id: uuid(), title: 'coffee cup' },
        { id: uuid(), title: 'floorsweeper' },
        { id: uuid(), title: 'boombox' },
        { id: uuid(), title: 'lantern' },
        { id: uuid(), title: 'ledger' },
        { id: uuid(), title: 'sake' },
        { id: uuid(), title: 'kanabo' },
        { id: uuid(), title: 'q-tip' },
        { id: uuid(), title: 'tech deck' },
        { id: uuid(), title: 'shuriken' },
        { id: uuid(), title: 'monk staff' },
        { id: uuid(), title: 'stylus' },
        { id: uuid(), title: 'fan' },
        { id: uuid(), title: 'fire' },
        { id: uuid(), title: 'lightning' },
        { id: uuid(), title: 'toothpick' },
        { id: uuid(), title: 'water' },
        { id: uuid(), title: 'earth' },
        { id: uuid(), title: 'paintbrush' },
        { id: uuid(), title: 'cards' },
        { id: uuid(), title: 'cigar' },
        { id: uuid(), title: 'match' },
        { id: uuid(), title: 'leaf' },
        { id: uuid(), title: 'guitar pick' },
        { id: uuid(), title: 'coin' },
        { id: uuid(), title: 'guitar' },
        { id: uuid(), title: 'round fan' },
        { id: uuid(), title: 'monkey king staff' },
        { id: uuid(), title: 'mahjong' },
        { id: uuid(), title: 'dart' },
        { id: uuid(), title: 'lipstick' },
        { id: uuid(), title: 'red bean' },
        { id: uuid(), title: 'fork' },
        { id: uuid(), title: 'lollipop' },
        { id: uuid(), title: 'basketball' },
        { id: uuid(), title: 'fox fire' },
        { id: uuid(), title: 'magic wand' },
        { id: uuid(), title: 'blue bean' },
        { id: uuid(), title: 'gold bean' },
        { id: uuid(), title: 'katana sheath' },
        { id: uuid(), title: 'golden coin' },
        { id: uuid(), title: 'boxing glove' },
        { id: uuid(), title: 'golden zanbato' },
        { id: uuid(), title: 'golden shuriken' },
        { id: uuid(), title: 'golden axe' },
        { id: uuid(), title: 'golden kanabo' },
        { id: uuid(), title: 'golden tech deck' },
        { id: uuid(), title: 'golden monk staff' },
        { id: uuid(), title: 'golden fork' },
        { id: uuid(), title: 'golden guitar' },
        { id: uuid(), title: 'golden sake' },
        { id: uuid(), title: 'golden monkey king staff' },
        { id: uuid(), title: 'golden lantern' },
        { id: uuid(), title: 'golden coffee cup' },
        { id: uuid(), title: 'golden cigar' },
        { id: uuid(), title: 'golden twig' },
        { id: uuid(), title: 'golden floorsweeper' },
        { id: uuid(), title: 'golden spray paint' },
        { id: uuid(), title: 'golden basketball' },
        { id: uuid(), title: 'golden cocktail umbrella' },
        { id: uuid(), title: 'golden toothpick' },
        { id: uuid(), title: 'golden leaf' },
        { id: uuid(), title: 'golden boombox' },
        { id: uuid(), title: 'golden stylus' },
        { id: uuid(), title: 'golden fan' },
        { id: uuid(), title: 'golden paintbrush' },
        { id: uuid(), title: 'golden cards' },
        { id: uuid(), title: 'golden magic wand' },
        { id: uuid(), title: 'golden dumbbell' },
        { id: uuid(), title: 'golden banner' },
        { id: uuid(), title: 'golden lollipop' },
        { id: uuid(), title: 'golden q-tip' },
        { id: uuid(), title: 'golden ledger' },
        { id: uuid(), title: 'golden boxing glove' },
        { id: uuid(), title: 'golden katana sheath' },
        { id: uuid(), title: 'golden mahjong' },
        { id: uuid(), title: 'golden dart' },
        { id: uuid(), title: 'golden guitar pick' },
        { id: uuid(), title: 'golden lipstick' },
        { id: uuid(), title: 'golden pencil' },
        { id: uuid(), title: 'golden round fan' },
      ],
    },
  },
  {
    id: uuid(),
    image: {
      azuki: generatorPath('azuki/hair.png'),
      bean: '',
    },
    title: 'hair',
    types: [types.azuki],
    children: {
      azuki: [
        { id: uuid(), title: 'maroon bun' },
        { id: uuid(), title: 'maroon ponytail' },
        { id: uuid(), title: 'brown spiky' },
        { id: uuid(), title: 'brown long' },
        { id: uuid(), title: 'maroon disheveled' },
        { id: uuid(), title: 'maroon bob' },
        { id: uuid(), title: 'magenta long' },
        { id: uuid(), title: 'indigo long' },
        { id: uuid(), title: 'maroon short spiky' },
        { id: uuid(), title: 'blonde short spiky' },
        { id: uuid(), title: 'blue spiky' },
        { id: uuid(), title: 'blonde long' },
        { id: uuid(), title: 'magenta pigtails' },
        { id: uuid(), title: 'powder blue pigtails' },
        { id: uuid(), title: 'blue short spiky' },
        { id: uuid(), title: 'green spiky' },
        { id: uuid(), title: 'orange short spiky' },
        { id: uuid(), title: 'black disheveled' },
        { id: uuid(), title: 'buzzcut' },
        { id: uuid(), title: 'purple spiky' },
        { id: uuid(), title: 'blonde flowy' },
        { id: uuid(), title: 'indigo ponytail' },
        { id: uuid(), title: 'green ponytail' },
        { id: uuid(), title: 'brown disheveled' },
        { id: uuid(), title: 'magenta flowy' },
        { id: uuid(), title: 'blonde bun' },
        { id: uuid(), title: 'teal bun' },
        { id: uuid(), title: 'purple bun' },
        { id: uuid(), title: 'indigo disheveled' },
        { id: uuid(), title: 'teal hairband' },
        { id: uuid(), title: 'brown ponytail' },
        { id: uuid(), title: 'blue bun' },
        { id: uuid(), title: 'blue half bun' },
        { id: uuid(), title: 'teal long' },
        { id: uuid(), title: 'maroon half bun' },
        { id: uuid(), title: 'green flowy' },
        { id: uuid(), title: 'green samurai' },
        { id: uuid(), title: 'orange pixie' },
        { id: uuid(), title: 'black pigtails' },
        { id: uuid(), title: 'indigo pixie' },
        { id: uuid(), title: 'blonde swept back' },
        { id: uuid(), title: 'orange samurai' },
        { id: uuid(), title: 'brown samurai' },
        { id: uuid(), title: 'purple pigtails' },
        { id: uuid(), title: 'blue samurai' },
        { id: uuid(), title: 'violet flowy' },
        { id: uuid(), title: 'silver ponytail' },
        { id: uuid(), title: 'brown flowy' },
        { id: uuid(), title: 'green pigtails' },
        { id: uuid(), title: 'blonde pixie' },
        { id: uuid(), title: 'brown half bun' },
        { id: uuid(), title: 'silver bun' },
        { id: uuid(), title: 'blue bob' },
        { id: uuid(), title: 'blonde messy' },
        { id: uuid(), title: 'teal messy' },
        { id: uuid(), title: 'orange swept back' },
        { id: uuid(), title: 'silver short spiky' },
        { id: uuid(), title: 'blue hairband' },
        { id: uuid(), title: 'powder blue disheveled' },
        { id: uuid(), title: 'silver disheveled' },
        { id: uuid(), title: 'brown messy' },
        { id: uuid(), title: 'blonde hairband' },
        { id: uuid(), title: 'pink flowy' },
        { id: uuid(), title: 'indigo messy' },
        { id: uuid(), title: 'magenta messy' },
        { id: uuid(), title: 'powder blue swept back' },
        { id: uuid(), title: 'indigo bangs' },
        { id: uuid(), title: 'silver pixie' },
        { id: uuid(), title: 'green half bun' },
        { id: uuid(), title: 'silver swept back' },
        { id: uuid(), title: 'long dreadlocks' },
        { id: uuid(), title: 'dreadlocks' },
        { id: uuid(), title: 'indigo swept back' },
        { id: uuid(), title: 'silver long' },
        { id: uuid(), title: 'blonde bob' },
        { id: uuid(), title: 'teal bob' },
        { id: uuid(), title: 'pink hairband' },
        { id: uuid(), title: 'black hairband' },
        { id: uuid(), title: 'maroon fluffy' },
        { id: uuid(), title: 'black bangs' },
        { id: uuid(), title: 'gray samurai' },
        { id: uuid(), title: 'teal bangs' },
        { id: uuid(), title: 'silver spiky' },
        { id: uuid(), title: 'silver flowy' },
        { id: uuid(), title: 'indigo fluffy' },
        { id: uuid(), title: 'brown bangs' },
        { id: uuid(), title: 'silver bob' },
        { id: uuid(), title: 'black swept back' },
        { id: uuid(), title: 'black fluffy' },
        { id: uuid(), title: 'green fluffy' },
        { id: uuid(), title: 'silver bangs' },
        { id: uuid(), title: 'silver hairband' },
        { id: uuid(), title: 'pink pixie' },
        { id: uuid(), title: 'green ombre bangs' },
        { id: uuid(), title: 'silver half bun' },
        { id: uuid(), title: 'brown fluffy' },
        { id: uuid(), title: 'pink bangs' },
        { id: uuid(), title: 'pink samurai' },
        { id: uuid(), title: 'silver dreadlocks' },
        { id: uuid(), title: 'blue pink ombre flowy' },
        { id: uuid(), title: 'purple dreadlocks' },
        { id: uuid(), title: 'black pink long' },
        { id: uuid(), title: 'blue nightshade half bun' },
        { id: uuid(), title: 'green teal long' },
        { id: uuid(), title: 'brown blonde flowy' },
        { id: uuid(), title: 'brown blonde long' },
        { id: uuid(), title: 'blue nightshade flowy' },
        { id: uuid(), title: 'braids' },
        { id: uuid(), title: 'purple bangs' },
        { id: uuid(), title: 'green ombre flowy' },
        { id: uuid(), title: 'purple half bun' },
        { id: uuid(), title: 'black teal bangs' },
        { id: uuid(), title: 'black orange bangs' },
        { id: uuid(), title: 'spirit spiky' },
        { id: uuid(), title: 'fire' },
        { id: uuid(), title: 'water' },
        { id: uuid(), title: 'brown dreadlocks' },
        { id: uuid(), title: 'spirit goddess' },
        { id: uuid(), title: 'spirit fluffy' },
        { id: uuid(), title: 'spirit ponytail' },
        { id: uuid(), title: 'spirit bob' },
        { id: uuid(), title: 'spirit long' },
        { id: uuid(), title: 'black blonde half bun' },
      ],
      bean: [],
    },
  },
  {
    id: uuid(),
    image: {
      azuki: generatorPath('headgear.png'),
      bean: generatorPath('headgear.png'),
    },
    title: 'headgear',
    types: [types.bean, types.azuki],
    children: {
      azuki: [
        { id: uuid(), title: 'ikz baseball cap' },
        { id: uuid(), title: 'full bandana' },
        { id: uuid(), title: 'yellow kanzashi' },
        { id: uuid(), title: 'purple kanzashi' },
        { id: uuid(), title: 'distressed beanie' },
        { id: uuid(), title: 'chef headband' },
        { id: uuid(), title: 'backwards cap' },
        { id: uuid(), title: 'black bucket hat' },
        { id: uuid(), title: 'pointy straw hat' },
        { id: uuid(), title: 'horns' },
        { id: uuid(), title: 'broken straw hat' },
        { id: uuid(), title: 'cowboy hat' },
        { id: uuid(), title: 'straw hat' },
        { id: uuid(), title: 'ayaigasa' },
        { id: uuid(), title: 'newsboy cap' },
        { id: uuid(), title: 'beret' },
        { id: uuid(), title: 'frog headband' },
        { id: uuid(), title: 'sandogasa' },
        { id: uuid(), title: 'cat headband' },
        { id: uuid(), title: 'sloth headband' },
        { id: uuid(), title: 'red panda baseball cap' },
        { id: uuid(), title: 'red panda headband' },
        { id: uuid(), title: 'fur bucket hat' },
        { id: uuid(), title: 'azuki cap' },
        { id: uuid(), title: 'sloth baseball cap' },
        { id: uuid(), title: 'frog baseball cap' },
        { id: uuid(), title: 'cat ears' },
        { id: uuid(), title: 'cat baseball cap' },
        { id: uuid(), title: 'sloth mask' },
        { id: uuid(), title: 'frog mask' },
        { id: uuid(), title: 'cat mask' },
        { id: uuid(), title: 'red panda mask' },
        { id: uuid(), title: 'sloth beanie' },
        { id: uuid(), title: 'cat beanie' },
        { id: uuid(), title: 'frog beanie' },
        { id: uuid(), title: 'red panda beanie' },
      ],
      bean: [
        { id: uuid(), title: 'sweatband' },
        { id: uuid(), title: 'black bucket hat' },
        { id: uuid(), title: 'beanie' },
        { id: uuid(), title: 'bean baseball cap' },
        { id: uuid(), title: 'trucker hat' },
        { id: uuid(), title: 'black toque' },
        { id: uuid(), title: 'red toque' },
        { id: uuid(), title: 'full bandana' },
        { id: uuid(), title: 'cowboy hat' },
        { id: uuid(), title: 'sloth beanie' },
        { id: uuid(), title: 'mcbean visor' },
        { id: uuid(), title: 'straw hat' },
        { id: uuid(), title: 'backwards cap' },
        { id: uuid(), title: 'frog bucket hat' },
        { id: uuid(), title: 'red panda baseball cap' },
        { id: uuid(), title: 'newsboy cap' },
        { id: uuid(), title: 'sushi chef' },
        { id: uuid(), title: 'fedora' },
        { id: uuid(), title: 'sloth headband' },
        { id: uuid(), title: 'faux fur trim bucket hat' },
        { id: uuid(), title: 'cat headband' },
        { id: uuid(), title: 'pointy straw hat' },
        { id: uuid(), title: 'kanzashi' },
        { id: uuid(), title: 'frog headband' },
        { id: uuid(), title: 'cat ears' },
        { id: uuid(), title: 'red panda headband' },
        { id: uuid(), title: 'cat mask' },
        { id: uuid(), title: 'red panda mask' },
        { id: uuid(), title: 'lotus leaf' },
        { id: uuid(), title: 'frog mask' },
        { id: uuid(), title: 'fisherman hat' },
        { id: uuid(), title: 'cat headphones' },
        { id: uuid(), title: 'trapper hat' },
        { id: uuid(), title: 'frog headphones' },
        { id: uuid(), title: 'red panda headphones' },
        { id: uuid(), title: 'sloth headphones' },
        { id: uuid(), title: 'jiang shi hat' },
        { id: uuid(), title: 'red hair bow' },
        { id: uuid(), title: 'red headband' },
        { id: uuid(), title: 'sloth mask' },
        { id: uuid(), title: 'soy sauce dish' },
        { id: uuid(), title: 'chauffeur cap' },
        { id: uuid(), title: 'white balaclava' },
        { id: uuid(), title: 'faux fur bucket hat' },
        { id: uuid(), title: 'horns' },
        { id: uuid(), title: 'monkey king crown' },
        { id: uuid(), title: 'red samurai helmet' },
        { id: uuid(), title: 'fire' },
        { id: uuid(), title: 'water' },
        { id: uuid(), title: 'chun bun' },
        { id: uuid(), title: 'black balaclava' },
        { id: uuid(), title: 'kappa - hair' },
        { id: uuid(), title: 'viking helmet' },
        { id: uuid(), title: 'black samurai helmet' },
        { id: uuid(), title: 'spartan helmet' },
        { id: uuid(), title: 'white bucket hat' },
      ],
    },
  },
  {
    id: uuid(),
    image: {
      azuki: generatorPath('face.png'),
      bean: generatorPath('face.png'),
    },
    title: 'face',
    types: [types.bean, types.azuki],
    children: {
      azuki: [
        { id: uuid(), title: 'red stripes face paint' },
        { id: uuid(), title: 'eye scar' },
        { id: uuid(), title: 'round blue sunglasses' },
        { id: uuid(), title: 'red fang face paint' },
        { id: uuid(), title: 'bandaid' },
        { id: uuid(), title: 'eye patch' },
        { id: uuid(), title: 'black glasses' },
        { id: uuid(), title: 'sleep mask' },
        { id: uuid(), title: 'reading glasses' },
        { id: uuid(), title: 'blue sunglasses' },
        { id: uuid(), title: 'kabuki facepaint' },
        { id: uuid(), title: 'clear glasses' },
        { id: uuid(), title: 'seer eyeband' },
        { id: uuid(), title: 'blush' },
        { id: uuid(), title: 'ji eyeband' },
        { id: uuid(), title: 'round purple sunglasses' },
        { id: uuid(), title: 'red bandana' },
        { id: uuid(), title: 'lipstick kiss' },
        { id: uuid(), title: 'heart eye patch' },
      ],
      bean: [
        { id: uuid(), title: 'round glasses' },
        { id: uuid(), title: 'blush' },
        { id: uuid(), title: 'bandaid' },
        { id: uuid(), title: 'shades' },
        { id: uuid(), title: 'clear glasses' },
        { id: uuid(), title: 'big glasses' },
        { id: uuid(), title: 'seer eyeband' },
        { id: uuid(), title: 'ji eyeband' },
        { id: uuid(), title: 'eye patch' },
        { id: uuid(), title: 'red stripes face paint' },
        { id: uuid(), title: 'red fang face paint' },
        { id: uuid(), title: 'tears' },
        { id: uuid(), title: 'sleep mask' },
        { id: uuid(), title: 'face mask' },
        { id: uuid(), title: 'kabuki face paint' },
        { id: uuid(), title: 'stubble' },
        { id: uuid(), title: 'nostrils - stubble' },
        { id: uuid(), title: 'monkey king face paint' },
      ],
    },
  },
  {
    id: uuid(),
    image: {
      azuki: generatorPath('azuki/neck.png'),
      bean: '',
    },
    title: 'neck',
    types: [types.azuki],
    children: {
      azuki: [
        { id: uuid(), title: 'chill headphones' },
        { id: uuid(), title: 'koi tattoo' },
        { id: uuid(), title: 'towel' },
        { id: uuid(), title: 'zen headphones' },
        { id: uuid(), title: 'beads' },
        { id: uuid(), title: 'tribal tattoo' },
        { id: uuid(), title: 'chain' },
        { id: uuid(), title: 'choker' },
        { id: uuid(), title: 'sneakers' },
        { id: uuid(), title: 'contract tattoo' },
        { id: uuid(), title: 'frog headphones' },
        { id: uuid(), title: 'red panda headphones' },
        { id: uuid(), title: 'cat headphones' },
        { id: uuid(), title: 'sloth headphones' },
        { id: uuid(), title: 'golden headphones' },
      ],
      bean: [],
    },
  },
  {
    id: uuid(),
    image: {
      azuki: generatorPath('azuki/eyes.png'),
      bean: generatorPath('eyes.png'),
    },
    title: 'eyes',
    types: [types.bean, types.azuki],
    children: {
      azuki: [
        { id: uuid(), title: 'closed' },
        { id: uuid(), title: 'determined' },
        { id: uuid(), title: 'striking' },
        { id: uuid(), title: 'chill' },
        { id: uuid(), title: 'daydreaming' },
        { id: uuid(), title: 'amethyst' },
        { id: uuid(), title: 'joyful' },
        { id: uuid(), title: 'concerned' },
        { id: uuid(), title: 'ruby' },
        { id: uuid(), title: 'careless' },
        { id: uuid(), title: 'calm' },
        { id: uuid(), title: 'tired' },
        { id: uuid(), title: 'hopeful' },
        { id: uuid(), title: 'indifferent' },
        { id: uuid(), title: 'curious' },
        { id: uuid(), title: 'relaxed' },
        { id: uuid(), title: 'focused' },
        { id: uuid(), title: 'bored' },
        { id: uuid(), title: 'pensive' },
        { id: uuid(), title: 'meditating' },
        { id: uuid(), title: 'suspicious' },
        { id: uuid(), title: 'pierced eyebrow' },
        { id: uuid(), title: 'white' },
        { id: uuid(), title: 'red' },
        { id: uuid(), title: 'glowing' },
        { id: uuid(), title: 'fire' },
        { id: uuid(), title: 'lightning' },
      ],
      bean: [
        { id: uuid(), title: 'closed' },
        { id: uuid(), title: 'dots' },
        { id: uuid(), title: 'half-open' },
        { id: uuid(), title: 'lashes' },
        { id: uuid(), title: 'stare' },
        { id: uuid(), title: 'friendly wink' },
        { id: uuid(), title: 'cheeky wink' },
        { id: uuid(), title: 'smile' },
        { id: uuid(), title: 'sad' },
        { id: uuid(), title: 'focused' },
        { id: uuid(), title: 'side eye' },
        { id: uuid(), title: ' confused' },
        { id: uuid(), title: 'sleep-deprived' },
        { id: uuid(), title: 'sussy' },
        { id: uuid(), title: 'dizzy' },
        { id: uuid(), title: 'cross-eyed' },
        { id: uuid(), title: 'blank' },
        { id: uuid(), title: 'pretty' },
        { id: uuid(), title: 'lightning' },
        { id: uuid(), title: 'fire' },
        { id: uuid(), title: 'spirit - dots' },
        { id: uuid(), title: 'spirit - closed' },
        { id: uuid(), title: 'spirit - determined' },
        { id: uuid(), title: 'spirit - lashes' },
        { id: uuid(), title: 'fire - blank' },
        { id: uuid(), title: 'black eye' },
      ],
    },
  },
  {
    id: uuid(),
    image: {
      azuki: generatorPath('mouth.png'),
      bean: generatorPath('mouth.png'),
    },
    title: 'mouth',
    types: [types.bean, types.azuki],
    children: {
      azuki: [
        { id: uuid(), title: 'relaxed' },
        { id: uuid(), title: 'closed' },
        { id: uuid(), title: 'smirk' },
        { id: uuid(), title: 'not bad' },
        { id: uuid(), title: 'smoking' },
        { id: uuid(), title: 'chuckle' },
        { id: uuid(), title: 'lipstick' },
        { id: uuid(), title: 'pout' },
        { id: uuid(), title: 'growl' },
        { id: uuid(), title: 'grass' },
        { id: uuid(), title: 'laughing' },
        { id: uuid(), title: 'meh' },
        { id: uuid(), title: 'smile' },
        { id: uuid(), title: 'frown' },
        { id: uuid(), title: 'grin' },
        { id: uuid(), title: 'chewing' },
        { id: uuid(), title: 'toothpick' },
        { id: uuid(), title: 'wheat straw' },
        { id: uuid(), title: 'whistling' },
        { id: uuid(), title: 'bubble gum' },
        { id: uuid(), title: 'tongue out' },
        { id: uuid(), title: 'face mask' },
        { id: uuid(), title: 'scroll' },
        { id: uuid(), title: '420' },
        { id: uuid(), title: 'tactical knife' },
        { id: uuid(), title: 'gaiter' },
        { id: uuid(), title: 'long stubble' },
        { id: uuid(), title: 'stubble' },
        { id: uuid(), title: 'sleep bubble' },
        { id: uuid(), title: 'surprised' },
      ],
      bean: [
        { id: uuid(), title: 'closed' },
        { id: uuid(), title: 'open smile' },
        { id: uuid(), title: 'smile' },
        { id: uuid(), title: 'nom' },
        { id: uuid(), title: 'kiss' },
        { id: uuid(), title: 'uwu' },
        { id: uuid(), title: 'buckteeth' },
        { id: uuid(), title: 'triangle' },
        { id: uuid(), title: 'wide happy smile' },
        { id: uuid(), title: 'wide toothy smile' },
        { id: uuid(), title: 'yum' },
        { id: uuid(), title: 'd:' },
        { id: uuid(), title: 'drool' },
        { id: uuid(), title: 'wide missing tooth smile' },
        { id: uuid(), title: 'wheat' },
        { id: uuid(), title: 'straw leaf' },
        { id: uuid(), title: 'cat' },
        { id: uuid(), title: 'grimace' },
        { id: uuid(), title: 'sleepy' },
        { id: uuid(), title: 'meh' },
        { id: uuid(), title: 'mustache - small' },
        { id: uuid(), title: 'whistling' },
        { id: uuid(), title: 'bubble gum' },
        { id: uuid(), title: 'missing tooth grimace' },
        { id: uuid(), title: 'mischievous' },
        { id: uuid(), title: 'frown' },
        { id: uuid(), title: 'spirit - closed' },
        { id: uuid(), title: 'gold grillz' },
        { id: uuid(), title: 'kappa - beak' },
        { id: uuid(), title: 'spirit - nom' },
        { id: uuid(), title: 'spirit - smile' },
        { id: uuid(), title: 'spirit - :c' },
        { id: uuid(), title: 'spirit - uwu' },
        { id: uuid(), title: 'spirit - kiss' },
        { id: uuid(), title: 'spirit - cat' },
        { id: uuid(), title: 'fire - :c' },
        { id: uuid(), title: 'fire - closed' },
        { id: uuid(), title: 'fire - cat' },
        { id: uuid(), title: 'fire - smile' },
        { id: uuid(), title: 'gus' },
        { id: uuid(), title: 'fire - nom' },
        { id: uuid(), title: 'fire - uwus' },
      ],
    },
  },
  {
    id: uuid(),
    image: {
      azuki: generatorPath('azuki/ear.png'),
      bean: '',
    },
    title: 'ear',
    types: [types.azuki],
    children: {
      azuki: [
        { id: uuid(), title: 'corded earbuds' },
        { id: uuid(), title: 'wireless earbuds' },
        { id: uuid(), title: 'ear cuffs' },
        { id: uuid(), title: 'chill' },
        { id: uuid(), title: 'stud' },
        { id: uuid(), title: 'spiked ring' },
        { id: uuid(), title: 'small hoop' },
        { id: uuid(), title: 'chiyogami' },
        { id: uuid(), title: 'red spiked ring' },
        { id: uuid(), title: 'yellow fan' },
        { id: uuid(), title: 'dragon' },
        { id: uuid(), title: 'skull ear cuffs' },
        { id: uuid(), title: 'yin yang' },
        { id: uuid(), title: 'wu' },
        { id: uuid(), title: 'blue fan' },
        { id: uuid(), title: 'sword' },
        { id: uuid(), title: 'sakura' },
        { id: uuid(), title: 'square stud' },
        { id: uuid(), title: 'ethereum' },
        { id: uuid(), title: 'sunflower' },
        { id: uuid(), title: 'red panda' },
        { id: uuid(), title: 'pearl' },
        { id: uuid(), title: 'red tassel' },
        { id: uuid(), title: 'red cylinder' },
        { id: uuid(), title: 'hoop' },
        { id: uuid(), title: 'blue tassel' },
        { id: uuid(), title: 'frog' },
        { id: uuid(), title: 'cat' },
        { id: uuid(), title: 'sloth' },
        { id: uuid(), title: 'blue cylinder' },
        { id: uuid(), title: 'blue bean' },
        { id: uuid(), title: 'red bean' },
      ],
      bean: [],
    },
  },
  {
    id: uuid(),
    image: {
      azuki: generatorPath('background.png'),
      bean: generatorPath('background.png'),
    },
    title: 'background',
    types: [types.bean, types.azuki],
    children: {
      azuki: [
        { id: uuid(), title: 'off white d' },
        { id: uuid(), title: 'off white c' },
        { id: uuid(), title: 'off white a' },
        { id: uuid(), title: 'off white b' },
        { id: uuid(), title: 'red' },
        { id: uuid(), title: 'dark blue' },
        { id: uuid(), title: 'cool gray' },
        { id: uuid(), title: 'dark purple' },
      ],
      bean: [
        { id: uuid(), title: 'off white d' },
        { id: uuid(), title: 'off white c' },
        { id: uuid(), title: 'off white a' },
        { id: uuid(), title: 'off white b' },
        { id: uuid(), title: 'red' },
        { id: uuid(), title: 'dark blue' },
        { id: uuid(), title: 'cool gray' },
        { id: uuid(), title: 'dark purple' },
      ],
    },
  },
];

export default galleryFilterList;
